case "$-" in "*i*") return ;; esac # non-interactive

. "/etc/bash/shit"

BUSYBOX_CMDS="
	realpath
	ls
	sed
	xargs
	basename
	rm
	date
	sort
	cut
	time
"
for cmd in ${BUSYBOX_CMDS}; do
	alias ${cmd}="busybox ${cmd}"
done

alias sdispatch-conf='sudo dispatch-conf'
alias svim='sudo vim'
alias semerge='sudo emerge'
alias rtorrent='rtorrent -n -o import=/etc/rtorrent.rc'
alias sxiv='sxiv -r -t'

ehistory() {
	eix '-I*' --format '<installedversions:DATESORT>' | sort -nr | cut -f2-3
}

viebuild() {
	local ebuilddir
	ebuilddir="$(eix "${@}" | eixpaths | peco)"
	[ $? -eq 0 ] || return $?
	vim "${ebuilddir}"
}

addpaths "${HOME}/bin" "${HOME}/.local/bin" "${HOME}/go/bin"
