#!/bin/sh

# .shit v1.1.2
# collection of shell utilities

[ "x${SHIT_SOURCED}" != "x" ] && return
SHIT_SOURCED=1

errcho() { (>&2 echo "${@}") }

addpaths() {
    for d in "${@}"; do
        [ -e "${d}" ] && export PATH="${PATH}:${d}"
    done
}

stfu() {
    "${@}" > /dev/null 2>&1
    return ${?}
}

if stfu pushd /tmp; then
    stfu popd
else
    export SHIT_PUSHD_STACK=""

    pushd() {
        [ "x${1}" = "x" ] && return 1
        export SHIT_PUSHD_STACK="${SHIT_PUSHD_STACK}:${PWD}"
        cd "${1}" || return 1
    }

    popd() {
        [ "x${SHIT_PUSHD_STACK}" = "x" ] && return 1
        [ "x${SHIT_PUSHD_STACK}" = "x:" ] && return 1
        cd "${SHIT_PUSHD_STACK##*:}" || return 1
        export SHIT_PUSHD_STACK="${SHIT_PUSHD_STACK%:*}"
    }
fi

doin() {
    stfu pushd "${1}"
    shift
    "${@}"
    result=${?}
    stfu popd
    return ${result}
}

# run a command and convert newline-separated output to quoted arguments
toargs() {
    "${@}" | xargs -I '{}' printf '"{}" '
}

# print the nth most recently modified file(s) in the current directory
#
# $ recent
# newest_file
#
# $ recent 1 3 4
# latest_file
# 3rd_latest_file
# 4th_latest_file
#
recent() {
    unset sedexp
    for n in "${@}"; do
        sedexp="${sedexp}${n}p;"
    done
    find . -maxdepth 1 -exec stat -c'%Z:%n' {} + \
    | sort -r \
    | cut -d':' -f2- \
    | sed /^\.$/d \
    | sed -n "${sedexp-1p;}"
}

autoname() {
    n=0
    basedir="${1-.}"
    while true; do
        name="${basedir}/$(date +%F_%H-%M-%S_${n})"
        [ ! -e "${name}" ] && break
        n=$((n + 1))
    done
    echo "${name}"
}

# vim: set syntax=sh expandtab softtabstop=0 listchars=tab\:>~,nbsp\:_,trail\:. list :
